# Generated by Django 4.2.3 on 2024-08-30 03:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("affiliation", models.CharField(default="Unknown", max_length=100)),
                ("qualifications", models.CharField(max_length=100)),
                ("about", models.TextField(default="No information provided")),
                ("hourly_rate", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="teacher_pictures/"
                    ),
                ),
                ("website", models.URLField(blank=True, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("email", models.EmailField(max_length=254)),
                ("country", models.CharField(max_length=100)),
                ("area", models.CharField(max_length=100)),
                (
                    "availability",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
